title: VIBE Conference 2023
preposition: at
description: >-
  Virtual Institute of Bioinformatics and Evolution, All-Ireland Conference 2023
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://VIBE2023.github.io" # the base hostname & protocol for your site, e.g. https://example.com
github_username:  VIBE2023
timezone: Europe/Dublin

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference"

# Build settings
plugins:
  [jekyll-include-cache]
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml
  - vendor

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    logo:
      name: QUB&Almac
      img: 'VIBE2023_ribbon_tp_small.png'
      #url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: Program
        relative_url: /program/
        disabled: true
      #- name: Talks
      #  relative_url: /talks/
      - name: Location
        relative_url: /location/
      - name: Attendees
      relative_url: /speakers/
      - name: Info
        relative_url: /info/
        disabled: true
      #- name: Register
      #  #relative_url: /register/
      #  absolute_url: 'https://docs.google.com/forms/d/e/1FAIpQLSeDlADcAg67SqH-oKPWU1LCDTU1WiNBEPfftLJnPFGz-oc_Ew/viewform?usp=sf_link'
      #  disabled: true
      - name: Previous Editions
        menu:
          - name: 2023 (current)
            disabled: true
          - name: 2022
            relative_url: https://vibe2022.github.io/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    img: 'VIBE2023.jpg'
    links:
      - name: Program
        relative_url: /program/
        disabled: true
      - name: How to get there
        relative_url: /location/
      #- name: Register Here
      #  disabled: true
      #  absolute_url: 'https://docs.google.com/forms/d/e/1FAIpQLSeDlADcAg67SqH-oKPWU1LCDTU1WiNBEPfftLJnPFGz-oc_Ew/viewform?usp=sf_link'

# Information boxes
  info_bars:
   - title: Registration closed
     color: primary
     main_only: true
     text: |
       Registration is now closed. If you would like to be added to the waitlist, please message vibe2023@qub.ac.uk. The conference program will shortly be made available.
  # Live indications
#  live:
#    date: 09.06.2022
#    timezone: Europe/Dublin
#    stop:       240  # in minutes
#    streaming:
#      enable: false
#      pause:     60  # in minutes
#      prepend:    5  # in minutes
#      extend:     5  # in minutes
#    demo:
#      enable: false
#      duration: 300  # in seconds
#      pause:     10  # in seconds

  map:
    # Initial map center point
    default_zoom: 17
    home_coord: 54.57646, -5.93488
    map_provider: "OpenStreetMap.Mapnik"
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: info 
      - name: Talk (8min)
        color: warning 
      - name: Lightning (1min)
        color: success
      - name: Other
        color: dark

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location /  overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 10 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false
